[package]
name = "crossui-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = ["login-app"]
login-app = ["dep:crossui-login-app"]

[dependencies]
crossui-core = { path = "../crossui-core" }
crossui-login-app = { path = "../../examples/login-app", optional = true }
serde_json.workspace = true
