package dev.crossui.compiler

import dev.crossui.ir.*
import dev.crossui.legalizer.ResolvedDocument

internal object ComposeGenerator : CodeGenerator {
    override val target = ExportTarget.JetpackCompose

    override fun generate(
        document: ResolvedDocument,
        typeName: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): List<GeneratedSource> {
        val body = composeNode(
            document.document.root,
            1,
            nativeViews,
            localization,
        )
        val stateType = document.document.stateType
        val actionType = document.document.actionType
        val stateParameter = stateType?.let {
            "state: ${it.substringAfterLast('.')}, "
        }.orEmpty()
        val stateImport = stateType
            ?.takeIf { '.' in it }
            ?.let { "import $it\n" }
            .orEmpty()
        val actionImport = actionType
            ?.takeIf { '.' in it && it != stateType }
            ?.let { "import $it\n" }
            .orEmpty()
        val connector = connector(typeName, stateType, actionType)
        val runtimeImports = if (connector.isNotEmpty()) {
            """
            |import dev.crossui.runtime.UiActionMapper
            |import dev.crossui.runtime.UiConnector
            |""".trimMargin() + "\n"
        } else {
            ""
        }
        val imageImport = if (
            document.document.root.anyNode { it.kind is NodeKind.Image }
        ) {
            "import coil.compose.AsyncImage\n"
        } else {
            ""
        }
        return listOf(
            GeneratedSource(
                target,
                target.outputFileName(typeName),
                """
                |// Generated by CrossUI. Do not edit.
                |package dev.crossui.generated
                |
                |import androidx.compose.foundation.layout.*
                |import androidx.compose.foundation.lazy.LazyColumn
                |import androidx.compose.foundation.lazy.items
                |import androidx.compose.foundation.text.KeyboardOptions
                |import androidx.compose.material3.*
                |import androidx.compose.runtime.*
                |import androidx.compose.ui.Modifier
                |import androidx.compose.ui.res.stringResource
                |import androidx.compose.ui.text.input.KeyboardType
                |import androidx.compose.ui.text.input.PasswordVisualTransformation
                |import androidx.compose.ui.unit.dp
                |$imageImport$runtimeImports$stateImport$actionImport
                |
                |@OptIn(ExperimentalMaterial3Api::class)
                |@Composable
                |fun $typeName(${stateParameter}dispatch: (action: String, value: String?) -> Unit) {
                |$body
                |}$connector
                |""".trimMargin(),
            ),
        )
    }

    private fun connector(
        typeName: String,
        stateType: String?,
        actionType: String?,
    ): String {
        if (stateType == null || actionType == null) return ""
        val stateName = stateType.substringAfterLast('.')
        val actionName = actionType.substringAfterLast('.')
        return """
        |
        |@Composable
        |fun $typeName(
        |    connector: UiConnector<$stateName, $actionName>,
        |    actions: UiActionMapper<$actionName>,
        |) {
        |    val state by connector.states.collectAsState()
        |    $typeName(state = state) { action, value ->
        |        connector.send(actions.map(action, value))
        |    }
        |}
        |""".trimMargin()
    }

    private fun composeNode(
        node: Node,
        depth: Int,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val i = "    ".repeat(depth)
        val marker = "$i// crossui-node:${node.key.value}\n"
        val child = { extra: Int ->
            node.children.joinToString("\n") {
                composeNode(it, depth + extra, nativeViews, localization)
            }
        }
        val generated = when (val kind = node.kind) {
            is NodeKind.Text -> text(node, kind, i, localization)
            is NodeKind.Button -> button(node, kind, i, localization)
            is NodeKind.Input -> input(node, kind, i, localization)
            is NodeKind.Stack -> {
                val layout = if (kind.axis == Axis.Horizontal) "Row" else "Column"
                val arrangement = if (kind.axis == Axis.Horizontal) {
                    "horizontalArrangement"
                } else {
                    "verticalArrangement"
                }
                "$i$layout($arrangement = Arrangement.spacedBy(${spacing(kind.spacing)}.dp)) {\n${child(1)}\n$i}"
            }
            is NodeKind.ListNode ->
                "$i${"LazyColumn { item {\n${child(2)}\n${"    ".repeat(depth + 1)}}\n$i}"}"
            NodeKind.Form ->
                "$i${"Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {\n${child(1)}\n$i}"}"
            is NodeKind.Loading -> "$i${"CircularProgressIndicator()"}"
            is NodeKind.Navigation ->
                navigation(node, kind, depth, i, nativeViews, localization)
            is NodeKind.Route ->
                "$i${"Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {\n${child(1)}\n$i}"}"
            is NodeKind.PlatformView -> nativeViews.render(
                target,
                kind.name,
                kind.payload.toString(),
            )?.prependIndent(i) ?: throw missingNativeView(kind.name, target)
            is NodeKind.Toggle ->
                "$i${"Row { Switch(checked = ${node.composeValue("checked", kind.checked.toString())}, onCheckedChange = { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) }, enabled = ${node.composeEnabled()})"}" +
                    (kind.label?.let {
                        "; Text(${node.composeText(LocalizedField.Label, it, localization)})"
                    } ?: "") + " }"
            is NodeKind.Image ->
                "$i${"AsyncImage(model = \"${kind.src.kotlin()}\", contentDescription = ${node.composeText(LocalizedField.Alt, kind.alt.orEmpty(), localization)})"}"
            is NodeKind.Dialog ->
                "$i${"AlertDialog(onDismissRequest = { dispatch(\"${kind.cancelAction.orEmpty().kotlin()}\", null) }, title = { Text(${node.composeText(LocalizedField.Title, kind.title, localization)}) }, confirmButton = { TextButton(onClick = { dispatch(\"${kind.confirmAction.orEmpty().kotlin()}\", null) }) { Text(${node.composeText(LocalizedField.ConfirmLabel, kind.confirmLabel.orEmpty(), localization)}) } }, dismissButton = { TextButton(onClick = { dispatch(\"${kind.cancelAction.orEmpty().kotlin()}\", null) }) { Text(${node.composeText(LocalizedField.CancelLabel, kind.cancelLabel.orEmpty(), localization)}) } })"}"
            is NodeKind.Slider ->
                "$i${"Slider(value = ${node.composeValue("value", "${kind.value}f")}, onValueChange = { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) }, valueRange = ${kind.min}f..${kind.max}f, enabled = ${node.composeEnabled()})"}"
            is NodeKind.Picker -> picker(node, kind, i, localization)
            is NodeKind.DatePicker -> datePicker(node, kind, i)
            is NodeKind.Checkbox ->
                "$i${"Row { Checkbox(checked = ${node.composeValue("checked", kind.checked.toString())}, onCheckedChange = { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) }, enabled = ${node.composeEnabled()})"}" +
                    (kind.label?.let {
                        "; Text(${node.composeText(LocalizedField.Label, it, localization)})"
                    } ?: "") + " }"
            NodeKind.Divider -> "${i}HorizontalDivider()"
            NodeKind.Card ->
                "$i${"Card { Column(Modifier.padding(16.dp)) {\n${child(2)}\n${"    ".repeat(depth + 1)}}\n$i}"}"
            is NodeKind.Chip -> chip(node, kind, i, localization)
        }
        val visible = node.bindings["visible"]
        val rendered = if (visible == null) {
            generated
        } else {
            "$i${"if (state.${visible.path}) {"}\n${generated.prependIndent("    ")}\n$i}"
        }
        return marker + rendered
    }

    private fun text(
        node: Node,
        kind: NodeKind.Text,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val value = node.composeValue(
            "value",
            node.composeText(LocalizedField.Value, kind.text, localization),
        )
        return "$i${"Text($value)"}"
    }

    private fun button(
        node: Node,
        kind: NodeKind.Button,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val name = when (kind.variant) {
            ButtonVariant.Primary -> "Button"
            ButtonVariant.Secondary -> "OutlinedButton"
            ButtonVariant.Destructive -> "Button"
        }
        val label = node.composeText(LocalizedField.Label, kind.label, localization)
        return "$i$name(onClick = { dispatch(\"${kind.action.kotlin()}\", null) }, enabled = ${node.composeEnabled()}) { Text($label) }"
    }

    private fun input(
        node: Node,
        kind: NodeKind.Input,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val keyboard =
            "KeyboardOptions(keyboardType = KeyboardType.${kind.inputType.composeKeyboard()})"
        val value = node.composeValue("value", "\"${kind.value.kotlin()}\"")
        val placeholder = node.composeText(
            LocalizedField.Placeholder,
            kind.placeholder.orEmpty(),
            localization,
        )
        val suffix = if (kind.secure || kind.inputType == InputType.Password) {
            ", visualTransformation = PasswordVisualTransformation())"
        } else {
            ")"
        }
        return "$i${"OutlinedTextField(value = $value, onValueChange = { dispatch(\"${kind.onChange.kotlin()}\", it) }, label = { Text($placeholder) }, enabled = ${node.composeEnabled()}, keyboardOptions = $keyboard"}$suffix"
    }

    private fun navigation(
        node: Node,
        kind: NodeKind.Navigation,
        depth: Int,
        i: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val selected = node.children.firstOrNull { it.key.value == kind.active }
            ?: node.children.firstOrNull()
        if (kind.mode != NavigationMode.Tab) {
            return selected?.let {
                composeNode(it, depth, nativeViews, localization)
            } ?: "${i}Spacer(Modifier)"
        }
        return "$i${"Column {\n${"    ".repeat(depth + 1)}NavigationBar {\n"}" +
            node.children.joinToString("\n") { route ->
                val title = (route.kind as? NodeKind.Route)?.title ?: route.key.value
                val label = route.composeText(
                    LocalizedField.Title,
                    title,
                    localization,
                )
                "${"    ".repeat(depth + 2)}NavigationBarItem(selected = ${route.key.value == kind.active}, onClick = { dispatch(\"navigate\", \"${route.key.value.kotlin()}\") }, icon = {}, label = { Text($label) })"
            } + "\n${"    ".repeat(depth + 1)}}\n" +
            selected?.let {
                composeNode(it, depth + 1, nativeViews, localization)
            }.orEmpty() + "\n$i}"
    }

    private fun picker(
        node: Node,
        kind: NodeKind.Picker,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val selected = kind.options
            .firstOrNull { it.value == kind.selected }
            ?.composeText(localization)
            ?: "\"\""
        return "$i${"Column { Text(${node.composeValue("selected", selected)})"}" +
            kind.options.joinToString("") {
                "; TextButton(onClick = { dispatch(\"${kind.onChange.kotlin()}\", \"${it.value.kotlin()}\") }) { Text(${it.composeText(localization)}) }"
            } + " }"
    }

    private fun datePicker(
        node: Node,
        kind: NodeKind.DatePicker,
        i: String,
    ): String {
        val variable = "dateState" + node.key.value.identifier()
        return "$i${"val $variable = rememberDatePickerState()"}\n" +
            "$i${"DatePicker(state = $variable)"}\n" +
            "$i${"LaunchedEffect($variable.selectedDateMillis) { $variable.selectedDateMillis?.let { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) } }"}"
    }

    private fun chip(
        node: Node,
        kind: NodeKind.Chip,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val label = node.composeText(LocalizedField.Label, kind.label, localization)
        val onDismiss = kind.onDismiss
        return if (onDismiss == null) {
            "$i${"AssistChip(onClick = {}, label = { Text($label) })"}"
        } else {
            "$i${"InputChip(selected = true, onClick = { dispatch(\"${onDismiss.kotlin()}\", null) }, label = { Text($label) })"}"
        }
    }
}
