package dev.crossui.compiler

import dev.crossui.ir.*
import dev.crossui.legalizer.ResolvedDocument

internal object ComposeGenerator : CodeGenerator {
    override val target = ExportTarget.JetpackCompose

    override fun generate(
        document: ResolvedDocument,
        typeName: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): List<GeneratedSource> {
        val rootVerticalScroll = !document.document.root.anyNode {
            it.kind is NodeKind.ListNode
        }
        val body = composeNode(
            document.document.root,
            2,
            nativeViews,
            localization,
            rootVerticalScroll,
        )
        val stateType = document.document.stateType
        val actionType = document.document.actionType
        val stateParameter = stateType?.let {
            "state: ${it.substringAfterLast('.')}, "
        }.orEmpty()
        val stateImport = stateType
            ?.takeIf { '.' in it }
            ?.let { "import $it\n" }
            .orEmpty()
        val actionImport = actionType
            ?.takeIf { '.' in it && it != stateType }
            ?.let { "import $it\n" }
            .orEmpty()
        val connector = connector(typeName, stateType, actionType)
        val themeAdapter = themeAdapter(typeName, document.document.theme)
        val runtimeImports = if (connector.isNotEmpty()) {
            """
            |import androidx.lifecycle.compose.collectAsStateWithLifecycle
            |import dev.crossui.runtime.UiActionMapper
            |import dev.crossui.runtime.UiConnector
            |""".trimMargin() + "\n"
        } else {
            ""
        }
        val imageImport = if (
            document.document.root.anyNode { it.kind is NodeKind.Image }
        ) {
            "import coil.compose.AsyncImage\n"
        } else {
            ""
        }
        val temporal = document.document.root.anyNode {
            it.kind is NodeKind.DatePicker
        }
        val temporalImports = if (temporal) {
            """
            |import java.text.SimpleDateFormat
            |import java.util.Date
            |import java.util.Locale
            |import java.util.TimeZone
            |""".trimMargin() + "\n"
        } else {
            ""
        }
        val temporalCodec = if (temporal) composeTemporalCodec() else ""
        val dynamicColorImports = if (
            document.document.theme.android.dynamicColor
        ) {
            """
            |import androidx.compose.foundation.isSystemInDarkTheme
            |import androidx.compose.ui.platform.LocalContext
            |""".trimMargin() + "\n"
        } else {
            ""
        }
        val additionalImports = listOf(
            imageImport,
            runtimeImports,
            stateImport,
            actionImport,
            temporalImports,
            dynamicColorImports,
        ).flatMap {
            it.lineSequence().filter(String::isNotBlank).toList()
        }
            .joinToString("\n")
        return listOf(
            GeneratedSource(
                target,
                target.outputFileName(typeName),
                """
                |// Generated by CrossUI. Do not edit.
                |package dev.crossui.generated
                |
                |import androidx.compose.foundation.layout.*
                |import androidx.compose.foundation.lazy.LazyColumn
                |import androidx.compose.foundation.lazy.items
                |import androidx.compose.foundation.rememberScrollState
                |import androidx.compose.foundation.text.KeyboardOptions
                |import androidx.compose.foundation.verticalScroll
                |import androidx.compose.material3.*
                |import androidx.compose.runtime.*
                |import androidx.compose.ui.Alignment
                |import androidx.compose.ui.Modifier
                |import androidx.compose.ui.res.stringResource
                |import androidx.compose.ui.text.input.KeyboardType
                |import androidx.compose.ui.text.input.PasswordVisualTransformation
                |import androidx.compose.ui.unit.dp
                |$additionalImports
                |
                |@OptIn(ExperimentalMaterial3Api::class)
                |@Composable
                |fun $typeName(${stateParameter}dispatch: (action: String, value: String?) -> Unit) {
                |    Box(Modifier.fillMaxSize(), contentAlignment = Alignment.TopCenter) {
                |$body
                |    }
                |}$connector$themeAdapter$temporalCodec
                |""".trimMargin().trimEnd() + "\n",
            ),
        )
    }

    private fun themeAdapter(typeName: String, theme: Theme): String {
        if (!theme.android.dynamicColor) return ""
        val dark = when (theme.colorScheme) {
            ColorScheme.System -> "isSystemInDarkTheme()"
            ColorScheme.Light -> "false"
            ColorScheme.Dark -> "true"
        }
        return """
        |
        |
        |@Composable
        |fun ${typeName}Theme(content: @Composable () -> Unit) {
        |    val context = LocalContext.current
        |    val colorScheme = if ($dark) {
        |        dynamicDarkColorScheme(context)
        |    } else {
        |        dynamicLightColorScheme(context)
        |    }
        |    MaterialTheme(colorScheme = colorScheme, content = content)
        |}
        |""".trimMargin()
    }

    private fun connector(
        typeName: String,
        stateType: String?,
        actionType: String?,
    ): String {
        if (stateType == null || actionType == null) return ""
        val stateName = stateType.substringAfterLast('.')
        val actionName = actionType.substringAfterLast('.')
        return """
        |
        |@Composable
        |fun $typeName(
        |    connector: UiConnector<$stateName, $actionName>,
        |    actions: UiActionMapper<$actionName>,
        |) {
        |    val state by connector.states.collectAsStateWithLifecycle()
        |    $typeName(state = state) { action, value ->
        |        connector.send(actions.map(action, value))
        |    }
        |}
        |""".trimMargin()
    }

    private fun composeNode(
        node: Node,
        depth: Int,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
        rootVerticalScroll: Boolean = false,
    ): String {
        val i = "    ".repeat(depth)
        val marker = "$i// crossui-node:${node.key.value}\n"
        val child = { extra: Int ->
            node.children.joinToString("\n") {
                composeNode(it, depth + extra, nativeViews, localization)
            }
        }
        val generated = when (val kind = node.kind) {
            is NodeKind.Text -> text(node, kind, i, localization)
            is NodeKind.Button -> button(node, kind, i, localization)
            is NodeKind.Input -> input(node, kind, i, localization)
            is NodeKind.Stack -> {
                val layout = if (kind.axis == Axis.Horizontal) "Row" else "Column"
                val arrangement = if (kind.axis == Axis.Horizontal) {
                    "horizontalArrangement"
                } else {
                    "verticalArrangement"
                }
                val modifier = rootScrollModifier(depth, rootVerticalScroll)
                "$i$layout($modifier$arrangement = Arrangement.spacedBy(${spacing(kind.spacing)}.dp)) {\n${child(1)}\n$i}"
            }
            is NodeKind.ListNode ->
                "$i${"LazyColumn { item {\n${child(2)}\n${"    ".repeat(depth + 1)}}\n$i}"}"
            NodeKind.Form ->
                "$i${"Column(${rootScrollModifier(depth, rootVerticalScroll)}verticalArrangement = Arrangement.spacedBy(16.dp)) {\n${child(1)}\n$i}"}"
            is NodeKind.Loading -> "$i${"CircularProgressIndicator()"}"
            is NodeKind.Navigation ->
                navigation(node, kind, depth, i, nativeViews, localization)
            is NodeKind.Route ->
                "$i${"Column(${rootScrollModifier(depth, rootVerticalScroll)}verticalArrangement = Arrangement.spacedBy(16.dp)) {\n${child(1)}\n$i}"}"
            is NodeKind.PlatformView -> nativeViews.render(
                target,
                kind.name,
                kind.payload.toString(),
            )?.prependIndent(i) ?: throw missingNativeView(kind.name, target)
            is NodeKind.Toggle ->
                "$i${"Row { Switch(checked = ${node.composeValue("checked", kind.checked.toString())}, onCheckedChange = { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) }, enabled = ${node.composeEnabled()})"}" +
                    (kind.label?.let {
                        "; Text(${node.composeText(LocalizedField.Label, it, localization)})"
                    } ?: "") + " }"
            is NodeKind.Image ->
                "$i${"AsyncImage(model = \"${kind.src.kotlin()}\", contentDescription = ${node.composeText(LocalizedField.Alt, kind.alt.orEmpty(), localization)})"}"
            is NodeKind.Dialog ->
                "$i${"AlertDialog(onDismissRequest = { dispatch(\"${kind.cancelAction.orEmpty().kotlin()}\", null) }, title = { Text(${node.composeText(LocalizedField.Title, kind.title, localization)}) }, confirmButton = { TextButton(onClick = { dispatch(\"${kind.confirmAction.orEmpty().kotlin()}\", null) }) { Text(${node.composeText(LocalizedField.ConfirmLabel, kind.confirmLabel.orEmpty(), localization)}) } }, dismissButton = { TextButton(onClick = { dispatch(\"${kind.cancelAction.orEmpty().kotlin()}\", null) }) { Text(${node.composeText(LocalizedField.CancelLabel, kind.cancelLabel.orEmpty(), localization)}) } })"}"
            is NodeKind.Slider ->
                "$i${"Slider(value = ${node.composeValue("value", "${kind.value}f")}, onValueChange = { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) }, valueRange = ${kind.min}f..${kind.max}f, enabled = ${node.composeEnabled()})"}"
            is NodeKind.Picker -> picker(node, kind, i, localization)
            is NodeKind.DatePicker -> datePicker(node, kind, i)
            is NodeKind.Checkbox ->
                "$i${"Row { Checkbox(checked = ${node.composeValue("checked", kind.checked.toString())}, onCheckedChange = { dispatch(\"${kind.onChange.kotlin()}\", it.toString()) }, enabled = ${node.composeEnabled()})"}" +
                    (kind.label?.let {
                        "; Text(${node.composeText(LocalizedField.Label, it, localization)})"
                    } ?: "") + " }"
            NodeKind.Divider -> "${i}HorizontalDivider()"
            NodeKind.Card ->
                "$i${"Card { Column(Modifier.padding(16.dp)) {\n${child(2)}\n${"    ".repeat(depth + 1)}}\n$i}"}"
            is NodeKind.Chip -> chip(node, kind, i, localization)
            is NodeKind.ContentPicker -> button(
                node,
                NodeKind.Button(kind.label, kind.onRequest, kind.variant),
                i,
                localization,
            )
        }
        val visible = node.bindings["visible"]
        val rendered = if (visible == null) {
            generated
        } else {
            "$i${"if (state.${visible.path}) {"}\n${generated.prependIndent("    ")}\n$i}"
        }
        return marker + rendered
    }

    private fun rootScrollModifier(
        depth: Int,
        enabled: Boolean,
    ): String = if (depth == 2 && enabled) {
        "modifier = Modifier.widthIn(max = 720.dp).fillMaxSize()" +
            ".verticalScroll(rememberScrollState()).padding(horizontal = 16.dp), "
    } else {
        ""
    }

    private fun text(
        node: Node,
        kind: NodeKind.Text,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val value = node.composeValue(
            "value",
            node.composeText(LocalizedField.Value, kind.text, localization),
        )
        return "$i${"Text($value)"}"
    }

    private fun button(
        node: Node,
        kind: NodeKind.Button,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val name = when (kind.variant) {
            ButtonVariant.Primary -> "Button"
            ButtonVariant.Secondary -> "OutlinedButton"
            ButtonVariant.Destructive -> "Button"
        }
        val label = node.composeText(LocalizedField.Label, kind.label, localization)
        return "$i$name(onClick = { dispatch(\"${kind.action.kotlin()}\", null) }, enabled = ${node.composeEnabled()}) { Text($label) }"
    }

    private fun input(
        node: Node,
        kind: NodeKind.Input,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val keyboard =
            "KeyboardOptions(keyboardType = KeyboardType.${kind.inputType.composeKeyboard()})"
        val value = node.composeValue("value", "\"${kind.value.kotlin()}\"")
        val placeholder = node.composeText(
            LocalizedField.Placeholder,
            kind.placeholder.orEmpty(),
            localization,
        )
        val suffix = if (kind.secure || kind.inputType == InputType.Password) {
            ", visualTransformation = PasswordVisualTransformation())"
        } else {
            ")"
        }
        return "$i${"OutlinedTextField(value = $value, onValueChange = { dispatch(\"${kind.onChange.kotlin()}\", it) }, label = { Text($placeholder) }, enabled = ${node.composeEnabled()}, keyboardOptions = $keyboard"}$suffix"
    }

    private fun navigation(
        node: Node,
        kind: NodeKind.Navigation,
        depth: Int,
        i: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val selected = node.children.firstOrNull { it.key.value == kind.active }
            ?: node.children.firstOrNull()
        if (kind.mode != NavigationMode.Tab) {
            return selected?.let {
                composeNode(it, depth, nativeViews, localization)
            } ?: "${i}Spacer(Modifier)"
        }
        val railItems = navigationItems(
            node,
            kind,
            depth + 3,
            localization,
            "NavigationRailItem",
        )
        val barItems = navigationItems(
            node,
            kind,
            depth + 3,
            localization,
            "NavigationBarItem",
        )
        val content = selected?.let {
            composeNode(it, depth + 2, nativeViews, localization)
        }.orEmpty()
        val contentName = "crossUiContent${node.key.value.identifier()}"
        val scroll = if (selected?.anyNode { it.kind is NodeKind.ListNode } == true) {
            ""
        } else {
            ".verticalScroll(rememberScrollState())"
        }
        return """
            |${i}BoxWithConstraints(Modifier.fillMaxSize()) {
            |${i}    val $contentName: @Composable () -> Unit = {
            |$content
            |${i}    }
            |${i}    if (maxWidth >= 600.dp) {
            |${i}        Row(Modifier.fillMaxSize()) {
            |${i}            NavigationRail {
            |$railItems
            |${i}            }
            |${i}            Box(Modifier.weight(1f).fillMaxHeight()$scroll.padding(horizontal = 24.dp), contentAlignment = Alignment.TopCenter) {
            |${i}                Box(Modifier.widthIn(max = 840.dp).fillMaxWidth()) {
            |${i}                    $contentName()
            |${i}                }
            |${i}            }
            |${i}        }
            |${i}    } else {
            |${i}        Column(Modifier.fillMaxSize()) {
            |${i}            Box(Modifier.weight(1f).fillMaxWidth()$scroll.padding(horizontal = 16.dp)) {
            |${i}                $contentName()
            |${i}            }
            |${i}            NavigationBar {
            |$barItems
            |${i}            }
            |${i}        }
            |${i}    }
            |${i}}
        """.trimMargin()
    }

    private fun navigationItems(
        node: Node,
        kind: NodeKind.Navigation,
        depth: Int,
        localization: LocalizationRegistry,
        component: String,
    ): String = node.children.joinToString("\n") { route ->
        val title = (route.kind as? NodeKind.Route)?.title ?: route.key.value
        val label = route.composeText(LocalizedField.Title, title, localization)
        "${"    ".repeat(depth)}$component(selected = " +
            "${route.key.value == kind.active}, onClick = { dispatch(\"navigate\", " +
            "\"${route.key.value.kotlin()}\") }, icon = {}, label = { Text($label) })"
    }

    private fun picker(
        node: Node,
        kind: NodeKind.Picker,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val selected = kind.options
            .firstOrNull { it.value == kind.selected }
            ?.composeText(localization)
            ?: "\"\""
        return "$i${"Column { Text(${node.composeValue("selected", selected)})"}" +
            kind.options.joinToString("") {
                "; TextButton(onClick = { dispatch(\"${kind.onChange.kotlin()}\", \"${it.value.kotlin()}\") }) { Text(${it.composeText(localization)}) }"
            } + " }"
    }

    private fun datePicker(
        node: Node,
        kind: NodeKind.DatePicker,
        i: String,
    ): String {
        val suffix = node.key.value.identifier()
        val value = "state.${requireNotNull(node.bindings["value"]).path}"
        val action = kind.onChange.kotlin()
        val ready = "temporalReady$suffix"
        val childIndent = "$i    "
        val content = when (kind.mode) {
            DatePickerMode.Date -> {
                val date = "dateState$suffix"
                "$childIndent${"var $ready by remember { mutableStateOf(false) }"}\n" +
                    "$childIndent${"val $date = rememberDatePickerState(initialSelectedDateMillis = CrossUiTemporalCodec.dateMillis($value))"}\n" +
                    "$childIndent${"DatePicker(state = $date)"}\n" +
                    "$childIndent${"LaunchedEffect($date.selectedDateMillis) { if ($ready) $date.selectedDateMillis?.let { dispatch(\"$action\", CrossUiTemporalCodec.date(it)) } else $ready = true }"}"
            }
            DatePickerMode.Time -> {
                val time = "timeState$suffix"
                "$childIndent${"var $ready by remember { mutableStateOf(false) }"}\n" +
                    "$childIndent${"val $time = rememberTimePickerState(initialHour = CrossUiTemporalCodec.hour($value), initialMinute = CrossUiTemporalCodec.minute($value))"}\n" +
                    "$childIndent${"TimePicker(state = $time)"}\n" +
                    "$childIndent${"LaunchedEffect($time.hour, $time.minute) { if ($ready) dispatch(\"$action\", CrossUiTemporalCodec.time($time.hour, $time.minute)) else $ready = true }"}"
            }
            DatePickerMode.DateTime -> {
                val date = "dateState$suffix"
                val time = "timeState$suffix"
                "$childIndent${"var $ready by remember { mutableStateOf(false) }"}\n" +
                    "$childIndent${"val $date = rememberDatePickerState(initialSelectedDateMillis = CrossUiTemporalCodec.dateMillis($value))"}\n" +
                    "$childIndent${"val $time = rememberTimePickerState(initialHour = CrossUiTemporalCodec.hour($value), initialMinute = CrossUiTemporalCodec.minute($value))"}\n" +
                    "$childIndent${"DatePicker(state = $date)"}\n" +
                    "$childIndent${"TimePicker(state = $time)"}\n" +
                    "$childIndent${"LaunchedEffect($date.selectedDateMillis, $time.hour, $time.minute) { if ($ready) $date.selectedDateMillis?.let { dispatch(\"$action\", CrossUiTemporalCodec.dateTime(it, $time.hour, $time.minute)) } else $ready = true }"}"
            }
        }
        return "$i${"key($value) {"}\n$content\n$i}"
    }

    private fun composeTemporalCodec(): String = """
        |
        |
        |private object CrossUiTemporalCodec {
        |    private val utc = TimeZone.getTimeZone("UTC")
        |
        |    fun dateMillis(value: String?): Long? {
        |        if (value.isNullOrBlank()) return null
        |        val pattern = if ('T' in value) "yyyy-MM-dd'T'HH:mm:ssX" else "yyyy-MM-dd"
        |        return formatter(pattern).parse(value)?.time
        |    }
        |
        |    fun hour(value: String?): Int =
        |        value?.substringAfter('T', value)?.take(2)?.toIntOrNull() ?: 0
        |
        |    fun minute(value: String?): Int =
        |        value?.substringAfter('T', value)?.drop(3)?.take(2)?.toIntOrNull() ?: 0
        |
        |    fun date(value: Long): String = formatter("yyyy-MM-dd").format(Date(value))
        |
        |    fun time(hour: Int, minute: Int): String =
        |        "%02d:%02d:00".format(Locale.ROOT, hour, minute)
        |
        |    fun dateTime(value: Long, hour: Int, minute: Int): String =
        |        "${'$'}{date(value)}T${'$'}{time(hour, minute)}Z"
        |
        |    private fun formatter(pattern: String) =
        |        SimpleDateFormat(pattern, Locale.ROOT).apply { timeZone = utc }
        |}
        |""".trimMargin()

    private fun chip(
        node: Node,
        kind: NodeKind.Chip,
        i: String,
        localization: LocalizationRegistry,
    ): String {
        val label = node.composeText(LocalizedField.Label, kind.label, localization)
        val onDismiss = kind.onDismiss
        return if (onDismiss == null) {
            "$i${"AssistChip(onClick = {}, label = { Text($label) })"}"
        } else {
            "$i${"InputChip(selected = true, onClick = { dispatch(\"${onDismiss.kotlin()}\", null) }, label = { Text($label) })"}"
        }
    }
}
