package dev.crossui.compiler

import dev.crossui.ir.*
import dev.crossui.legalizer.ResolvedDocument

internal object SwiftUiGenerator : CodeGenerator {
    override val target = ExportTarget.SwiftUi

    override fun generate(
        document: ResolvedDocument,
        typeName: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): List<GeneratedSource> {
        val adaptiveContent = document.document.root.kind !is NodeKind.Navigation &&
            document.document.root.kind !is NodeKind.ListNode
        val body = swiftNode(
            document.document.root,
            if (adaptiveContent) 3 else 2,
            nativeViews,
            localization,
        ).let {
            if (adaptiveContent) {
                "        ${typeName}AdaptiveContent {\n$it\n        }"
            } else {
                it
            }
        }
        val stateType = document.document.stateType
        val actionType = document.document.actionType
        val state = stateType?.let {
            "    let state: ${it.substringAfterLast('.')}\n"
        }.orEmpty()
        val connector = if (stateType != null && actionType != null) {
            swiftConnector(
                typeName = typeName,
                stateName = stateType.substringAfterLast('.'),
                actionName = actionType.substringAfterLast('.'),
                settings = document.document.settings,
            )
        } else {
            ""
        }
        val temporalCodec = if (
            document.document.root.anyNode { it.kind is NodeKind.DatePicker }
        ) {
            swiftTemporalCodec()
        } else {
            ""
        }
        val adaptiveHelper = if (adaptiveContent) {
            swiftAdaptiveContent(typeName)
        } else {
            ""
        }
        val keyboardHelper = if (document.document.root.anyNode {
                (it.kind as? NodeKind.Input)?.inputType in platformKeyboards
            }
        ) swiftKeyboardSupport() else ""
        return listOf(
            GeneratedSource(
                target,
                target.outputFileName(typeName),
                """
                |// Generated by CrossUI. Do not edit.
                |// The typed state/action boundary is supplied by the Swift-exported KMP
                |// module: State is a Swift value type, Action is a Swift enum, and
                |// observation is @MainActor. No ObjC bridging or runtime UI interpreter
                |// is used. See swiftExport in the feature build script.
                |import Foundation
                |import SwiftUI
                |import Observation
                |
                |struct $typeName: View {
                |$state
                |    let dispatch: (_ action: String, _ value: String?) -> Void
                |
                |    var body: some View {
                |$body
                |    }
                |}$connector$adaptiveHelper$keyboardHelper$temporalCodec
                |""".trimMargin().trimEnd() + "\n",
            ),
        )
    }

    private fun swiftConnector(
        typeName: String,
        stateName: String,
        actionName: String,
        settings: List<SettingDeclaration>,
    ): String {
        val appStorageSettings = settings.filter {
            it.ownership == SettingOwnership.PlatformUi &&
                it.storage == SettingStorage.Preferences
        }
        val storageProperties = appStorageSettings.joinToString("\n") { setting ->
            val name = setting.swiftStorageName()
            val type = setting.swiftType()
            val default = setting.swiftDefault()
            "    @AppStorage(\"${setting.key.swift()}\") private var $name: $type = $default"
        }.let { if (it.isEmpty()) "" else "\n$it" }
        val storageModifiers = appStorageSettings.joinToString("") { setting ->
            val stored = setting.swiftStorageName()
            val state = "model.state.${setting.statePath}"
            val serializedValue = when (setting.valueType) {
                SettingValueType.String -> "value"
                else -> "String(value)"
            }
            """
            |
            |        .onAppear {
            |            if $state != $stored {
            |                model.dispatch(actions("${setting.onChange.swift()}", ${setting.swiftSerialized(stored)}))
            |            }
            |        }
            |        .onChange(of: $stored) { _, value in
            |            if $state != value {
            |                model.dispatch(actions("${setting.onChange.swift()}", $serializedValue))
            |            }
            |        }
            |        .onChange(of: $state) { _, value in
            |            if $stored != value {
            |                $stored = value
            |            }
            |        }
            |""".trimMargin()
        }.trimEnd()
        return """
        |
        |
        |@MainActor
        |@Observable
        |final class ${typeName}Model {
        |    private(set) var state: $stateName
        |    private let send: ($actionName) -> Void
        |    private var cancelObservation: (() -> Void)?
        |
        |    init(
        |        initialState: $stateName,
        |        observe: (@escaping @MainActor ($stateName) -> Void) -> (() -> Void),
        |        send: @escaping ($actionName) -> Void
        |    ) {
        |        self.state = initialState
        |        self.send = send
        |        self.cancelObservation = observe { [weak self] nextState in
        |            self?.state = nextState
        |        }
        |    }
        |
        |    func dispatch(_ action: $actionName) {
        |        send(action)
        |    }
        |
        |    func cancel() {
        |        cancelObservation?()
        |        cancelObservation = nil
        |    }
        |}
        |
        |struct ${typeName}Connected: View {
        |    @Bindable var model: ${typeName}Model
        |    let actions: (_ action: String, _ value: String?) -> $actionName$storageProperties
        |
        |    var body: some View {
        |        $typeName(state: model.state) { action, value in
        |            model.dispatch(actions(action, value))
        |        }$storageModifiers
        |    }
        |}
        |""".trimMargin()
    }

    private fun swiftNode(
        node: Node,
        depth: Int,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val i = "    ".repeat(depth)
        val marker = "$i// crossui-node:${node.key.value}\n"
        val child = { extra: Int ->
            node.children.joinToString("\n") {
                swiftNode(it, depth + extra, nativeViews, localization)
            }
        }
        val generated = when (val kind = node.kind) {
            is NodeKind.Text -> {
                val style = when (kind.style) {
                    TextStyle.Display -> ".largeTitle"
                    TextStyle.Headline -> ".headline"
                    TextStyle.Title -> ".title"
                    TextStyle.Body -> ".body"
                    TextStyle.Caption -> ".caption"
                    TextStyle.Footnote -> ".footnote"
                }
                val value = node.swiftValue(
                    "value",
                    node.swiftText(LocalizedField.Value, kind.text, localization),
                )
                "$i${"Text($value)"}.font($style)"
            }
            is NodeKind.Button -> {
                val role = if (kind.variant == ButtonVariant.Destructive) {
                    ", role: .destructive"
                } else {
                    ""
                }
                val label = node.swiftText(
                    LocalizedField.Label,
                    kind.label,
                    localization,
                )
                "$i${"Button($label$role) { dispatch(\"${kind.action.swift()}\", nil) }"}" +
                    kind.variant.swiftButtonStyle() + enabled(node) +
                    accessibility(node) + keyboardShortcut(node)
            }
            is NodeKind.Input -> {
                val prompt = node.swiftText(
                    LocalizedField.Placeholder,
                    kind.placeholder.orEmpty(),
                    localization,
                )
                val value = node.bindings["value"]?.let {
                    "Binding(get: { state.${it.path} }, set: { dispatch(\"${kind.onChange.swift()}\", \$0) })"
                } ?: ".constant(\"${kind.value.swift()}\")"
                val field = if (kind.secure || kind.inputType == InputType.Password) {
                    "SecureField($prompt, text: $value)"
                } else {
                    "TextField($prompt, text: $value)"
                }
                "$i$field${keyboard(kind.inputType)}${submit(kind.returnKey)}" +
                    enabled(node) + accessibility(node)
            }
            is NodeKind.Stack -> {
                val stack = if (kind.axis == Axis.Horizontal) "HStack" else "VStack"
                "$i$stack(${kind.swiftStackAlignment()}spacing: ${spacing(kind.spacing)}) {\n${child(1)}\n$i}" +
                    kind.swiftStretch()
            }
            is NodeKind.ListNode ->
                "$i${"List {\n${child(1)}\n$i}"}.onTapGesture { dispatch(\"${kind.onSelect.orEmpty().swift()}\", nil) }"
            NodeKind.Form ->
                "$i${ "Form {\n${child(1)}\n$i}" }" +
                    "\n#if os(iOS) || os(macOS)\n.formStyle(.grouped)\n#endif"
            is NodeKind.Loading -> {
                val label = node.swiftText(
                    LocalizedField.Label,
                    kind.label.orEmpty(),
                    localization,
                )
                "$i${"ProgressView($label)"}"
            }
            is NodeKind.Navigation ->
                navigation(node, kind, depth, i, nativeViews, localization)
            is NodeKind.Route -> swiftRouteLayout(
                node = node,
                kind = kind,
                indentation = i,
                children = child(2),
                title = node.swiftText(LocalizedField.Title, kind.title, localization),
            )
            is NodeKind.PlatformView -> nativeViews.render(
                target,
                kind.name,
                kind.payload.toString(),
            )?.prependIndent(i) ?: throw missingNativeView(kind.name, target)
            is NodeKind.Toggle ->
                "$i${"Toggle(${node.swiftText(LocalizedField.Label, kind.label.orEmpty(), localization)}, isOn: ${node.swiftBinding("checked", kind.checked.toString(), kind.onChange)})"}" +
                    enabled(node) + accessibility(node)
            is NodeKind.Image ->
                "$i${"AsyncImage(url: URL(string: \"${kind.src.swift()}\"))"}.accessibilityLabel(" +
                    node.swiftText(LocalizedField.Alt, kind.alt.orEmpty(), localization) + ")"
            is NodeKind.Dialog -> dialog(node, kind, depth, i, child, localization)
            is NodeKind.Slider ->
                "$i${"Slider(value: ${node.swiftBinding("value", kind.value.toString(), kind.onChange)}, in: ${kind.min}...${kind.max}, step: ${kind.step ?: 1.0})"}" +
                    enabled(node) + accessibility(node)
            is NodeKind.Picker ->
                "$i${"Picker(\"\", selection: ${node.swiftBinding("selected", "\"${kind.selected.swift()}\"", kind.onChange)}) {\n"}" +
                    kind.options.joinToString("\n") {
                        "${"    ".repeat(depth + 1)}Text(${it.swiftText(localization)}).tag(\"${it.value.swift()}\")"
                    } + "\n$i}"
            is NodeKind.DatePicker ->
                datePicker(node, kind, i)
            is NodeKind.Checkbox ->
                "$i${"Button { dispatch(\"${kind.onChange.swift()}\", String(!${node.swiftValue("checked", kind.checked.toString())})) } label: { Label(${node.swiftText(LocalizedField.Label, kind.label.orEmpty(), localization)}, systemImage: ${node.swiftValue("checked", kind.checked.toString())} ? \"checkmark.square.fill\" : \"square\") }"}" +
                    enabled(node) + accessibility(node)
            NodeKind.Divider -> "${i}Divider()"
            NodeKind.Card -> "$i${"GroupBox {\n${child(1)}\n$i}"}"
            is NodeKind.Chip ->
                "$i${"HStack { Text(${node.swiftText(LocalizedField.Label, kind.label, localization)})"}" +
                    (kind.onDismiss?.let {
                        "; Button { dispatch(\"${it.swift()}\", nil) } label: { Image(systemName: \"xmark\") }"
                    } ?: "") + " }"
            is NodeKind.ContentPicker -> {
                val role = if (kind.variant == ButtonVariant.Destructive) {
                    ", role: .destructive"
                } else {
                    ""
                }
                val label = node.swiftText(LocalizedField.Label, kind.label, localization)
                "$i${"Button($label$role) { dispatch(\"${kind.onRequest.swift()}\", nil) }"}" +
                    kind.variant.swiftButtonStyle() + enabled(node) +
                    accessibility(node) + keyboardShortcut(node)
            }
        }
        val visible = node.bindings["visible"]
        val rendered = if (visible == null) {
            generated
        } else {
            "$i${"if state.${visible.path} {"}\n${generated.prependIndent("    ")}\n$i}"
        }
        return marker + rendered
    }

    private fun datePicker(
        node: Node,
        kind: NodeKind.DatePicker,
        indentation: String,
    ): String {
        val path = requireNotNull(node.bindings["value"]).path
        val mode = when (kind.mode) {
            DatePickerMode.Date -> "date"
            DatePickerMode.Time -> "time"
            DatePickerMode.DateTime -> "dateTime"
        }
        val components = when (kind.mode) {
            DatePickerMode.Date -> ".date"
            DatePickerMode.Time -> ".hourAndMinute"
            DatePickerMode.DateTime -> "[.date, .hourAndMinute]"
        }
        val binding =
            "Binding(get: { CrossUiTemporalCodec.decode(state.$path, mode: .$mode) }, " +
                "set: { dispatch(\"${kind.onChange.swift()}\", " +
                "CrossUiTemporalCodec.encode(\$0, mode: .$mode)) })"
        return "$indentation" +
            "DatePicker(\"\", selection: $binding, displayedComponents: $components)"
    }

    private fun swiftTemporalCodec(): String = """
        |
        |
        |@MainActor
        |private enum CrossUiTemporalCodec {
        |    enum Mode {
        |        case date
        |        case time
        |        case dateTime
        |    }
        |
        |    static func decode(_ value: String?, mode: Mode) -> Date {
        |        guard let value, !value.isEmpty else { return Date() }
        |        switch mode {
        |        case .date:
        |            return formatter("yyyy-MM-dd").date(from: value) ?? Date()
        |        case .time:
        |            return formatter("HH:mm:ss").date(from: value) ?? Date()
        |        case .dateTime:
        |            return ISO8601DateFormatter().date(from: value) ?? Date()
        |        }
        |    }
        |
        |    static func encode(_ value: Date, mode: Mode) -> String {
        |        switch mode {
        |        case .date:
        |            return formatter("yyyy-MM-dd").string(from: value)
        |        case .time:
        |            return formatter("HH:mm:ss").string(from: value)
        |        case .dateTime:
        |            return ISO8601DateFormatter().string(from: value)
        |        }
        |    }
        |
        |    private static func formatter(_ format: String) -> DateFormatter {
        |        let formatter = DateFormatter()
        |        formatter.locale = Locale(identifier: "en_US_POSIX")
        |        formatter.dateFormat = format
        |        return formatter
        |    }
        |}
        |""".trimMargin()

    private fun navigation(
        node: Node,
        kind: NodeKind.Navigation,
        depth: Int,
        indentation: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val selected = node.children.firstOrNull { it.key.value == kind.active }
            ?: node.children.firstOrNull()
        return if (kind.mode == NavigationMode.Tab) {
            val selection = node.bindings["active"]?.let {
                "(selection: Binding(get: { state.${it.path} }, " +
                    "set: { dispatch(\"${kind.onChange.swift()}\", \$0) }))"
            }.orEmpty()
            "$indentation${"TabView$selection {\n"}" +
                node.children.joinToString("\n") { route ->
                    val title = (route.kind as? NodeKind.Route)?.title ?: route.key.value
                    swiftNode(route, depth + 1, nativeViews, localization) +
                        ".tabItem { Text(${route.swiftText(LocalizedField.Title, title, localization)}) }" +
                        if (selection.isEmpty()) "" else ".tag(\"${route.key.value.swift()}\")"
                } + "\n$indentation}" +
                    "\n#if os(iOS) || os(macOS)" +
                    "\n$indentation    .tabViewStyle(.sidebarAdaptable)" +
                    "\n#endif"
        } else {
            "$indentation${"NavigationStack {\n${selected?.let { swiftNode(it, depth + 1, nativeViews, localization) }.orEmpty()}\n$indentation}"}"
        }
    }

    private fun dialog(
        node: Node,
        kind: NodeKind.Dialog,
        depth: Int,
        indentation: String,
        child: (Int) -> String,
        localization: LocalizationRegistry,
    ): String {
        val body = child(1).ifBlank {
            "${"    ".repeat(depth + 1)}EmptyView()"
        }
        return "$indentation${"VStack {\n$body\n$indentation}"}.confirmationDialog(" +
            node.swiftText(LocalizedField.Title, kind.title, localization) +
            ", isPresented: .constant(true)) {\n" +
            listOfNotNull(
                kind.confirmLabel?.let {
                    "${"    ".repeat(depth + 1)}Button(" +
                        node.swiftText(
                            LocalizedField.ConfirmLabel,
                            it,
                            localization,
                        ) +
                        ") { dispatch(\"${kind.confirmAction.orEmpty().swift()}\", nil) }"
                },
                kind.cancelLabel?.let {
                    "${"    ".repeat(depth + 1)}Button(" +
                        node.swiftText(
                            LocalizedField.CancelLabel,
                            it,
                            localization,
                        ) +
                        ", role: .cancel) { dispatch(\"${kind.cancelAction.orEmpty().swift()}\", nil) }"
                },
            ).joinToString("\n") + "\n$indentation}"
    }

    private fun enabled(node: Node): String {
        val binding = node.bindings["enabled"]
        return when {
            binding != null -> ".disabled(!state.${binding.path})"
            node.semantics.enabled -> ""
            else -> ".disabled(true)"
        }
    }

    private fun accessibility(node: Node) =
        node.semantics.label?.let {
            ".accessibilityLabel(\"${it.swift()}\")"
        }.orEmpty()

    private fun keyboardShortcut(node: Node): String {
        val shortcut = node.extensions
            .filterIsInstance<PlatformExtension.MacOs>()
            .map { it.value }
            .filterIsInstance<MacOsExtension.KeyboardShortcut>()
            .firstOrNull()
            ?: return ""
        val modifiers = shortcut.modifiers.joinToString(", ") {
            ".${it.name.lowercase()}"
        }
        val body = if (modifiers.isEmpty()) {
            ".keyboardShortcut(\"${shortcut.key.swift()}\")"
        } else {
            ".keyboardShortcut(\"${shortcut.key.swift()}\", modifiers: [$modifiers])"
        }
        // Keyboard shortcuts exist only on iOS and macOS; watchOS, tvOS, and
        // visionOS compile the modifier out so the generated view stays portable.
        return "\n#if os(iOS) || os(macOS)\n$body\n#endif"
    }

    private fun keyboard(type: InputType) = when (type) {
        InputType.Email -> ".crossUiKeyboard(.email)"
        InputType.Number -> ".crossUiKeyboard(.number)"
        InputType.Phone -> ".crossUiKeyboard(.phone)"
        InputType.Url -> ".crossUiKeyboard(.url)"
        else -> ""
    }

    private fun submit(key: ReturnKey?) = key?.let {
        // .submitLabel is iOS/macOS only; other Apple platforms compile it out.
        // The trailing newline keeps the following modifier on its own line.
        "\n#if os(iOS) || os(macOS)\n.submitLabel(.${it.name.lowercase()})\n#endif\n"
    }.orEmpty()
}
