package dev.crossui.compiler

import dev.crossui.ir.*
import dev.crossui.legalizer.ResolvedDocument

internal object WinUiGenerator : CodeGenerator {
    override val target = ExportTarget.WinUi3

    override fun generate(
        document: ResolvedDocument,
        typeName: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): List<GeneratedSource> {
        val rootIsNavigation = document.document.root.kind is NodeKind.Navigation
        val body = xamlNode(
            document.document.root,
            if (rootIsNavigation) 1 else 4,
            nativeViews,
            localization,
        )
        return listOf(
            GeneratedSource(
                target,
                target.outputFileName(typeName),
                """
                |<!-- Generated by CrossUI. Do not edit. -->
                |<UserControl
                |    x:Class="CrossUi.Generated.$typeName"
                |    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                |    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
                |${winUiRootLayout(typeName, body, rootIsNavigation)}
                |</UserControl>
                |""".trimMargin(),
            ),
            GeneratedSource(
                target,
                "$typeName.xaml.cs",
                codeBehind(document.document, typeName, localization),
            ),
        )
    }

    private fun xamlNode(
        node: Node,
        depth: Int,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val i = "    ".repeat(depth)
        val marker = "$i<!-- crossui-node:${node.key.value} -->\n"
        val child = { extra: Int ->
            node.children.joinToString("\n") {
                xamlNode(it, depth + extra, nativeViews, localization)
            }
        }
        val enabled = node.bindings["enabled"]?.let {
            " IsEnabled=\"{x:Bind State.${it.path.replaceFirstChar(Char::uppercaseChar)}, Mode=OneWay}\""
        } ?: if (node.semantics.enabled) "" else " IsEnabled=\"False\""
        val visibleBinding = node.bindings["visible"]
        val outerVisibility = visibleBinding?.let {
            " Visibility=\"{x:Bind BooleanToVisibility(State.${it.path.replaceFirstChar(Char::uppercaseChar)}), Mode=OneWay}\""
        }.orEmpty()
        val visible = if (visibleBinding == null) outerVisibility else ""
        val automation = node.semantics.label?.let {
            " AutomationProperties.Name=\"${it.xml()}\""
        }.orEmpty()
        val generated = when (val kind = node.kind) {
            is NodeKind.Text ->
                "$i<TextBlock Text=\"${node.xamlValue("value", node.xamlText(LocalizedField.Value, kind.text), "OneWay")}\" Style=\"{ThemeResource ${kind.style.winUiTextStyle()}}\" TextWrapping=\"Wrap\"$visible$automation />"
            is NodeKind.Button ->
                "$i<Button Content=\"${node.xamlText(LocalizedField.Label, kind.label)}\" Tag=\"${kind.action.xml()}\" Click=\"OnAction\"${kind.variant.winUiButtonStyle()}$visible$enabled$automation />"
            is NodeKind.Input -> input(node, kind, i, visible, enabled, automation)
            is NodeKind.Stack -> {
                val orientation = if (kind.axis == Axis.Horizontal) {
                    "Horizontal"
                } else {
                    "Vertical"
                }
                "$i<StackPanel Orientation=\"$orientation\" Spacing=\"${spacing(kind.spacing)}\">\n${child(1)}\n$i</StackPanel>"
            }
            is NodeKind.ListNode ->
                "$i<StackPanel Tag=\"${kind.onSelect.orEmpty().xml()}\">\n${child(1)}\n$i</StackPanel>"
            NodeKind.Form -> "$i<StackPanel Spacing=\"16\">\n${child(1)}\n$i</StackPanel>"
            is NodeKind.Loading -> "$i<ProgressRing IsActive=\"True\"$visible />"
            is NodeKind.Navigation ->
                winUiNavigation(node, kind, depth, i) { route, routeDepth ->
                    xamlNode(route, routeDepth, nativeViews, localization)
                }
            is NodeKind.Route ->
                "$i<StackPanel Spacing=\"16\">\n${child(1)}\n$i</StackPanel>"
            is NodeKind.PlatformView -> nativeViews.render(
                target,
                kind.name,
                kind.payload.toString(),
            )?.prependIndent(i) ?: throw missingNativeView(kind.name, target)
            is NodeKind.Toggle ->
                "$i<ToggleSwitch Header=\"${node.xamlText(LocalizedField.Label, kind.label.orEmpty())}\" IsOn=\"${node.xamlValue("checked", kind.checked.toString())}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("checked" in node.bindings) "" else " Toggled=\"OnToggleChanged\"") +
                    "$visible$enabled$automation />"
            is NodeKind.Image ->
                "$i<Image Source=\"${kind.src.xml()}\" AutomationProperties.Name=\"${node.xamlText(LocalizedField.Alt, kind.alt.orEmpty())}\" />"
            is NodeKind.Dialog ->
                "$i<!-- ContentDialog Title=\"${kind.title.xml()}\" PrimaryButtonText=\"${kind.confirmLabel.orEmpty().xml()}\" CloseButtonText=\"${kind.cancelLabel.orEmpty().xml()}\" -->"
            is NodeKind.Slider ->
                "$i<Slider Value=\"${node.xamlValue("value", kind.value.toString())}\" Minimum=\"${kind.min}\" Maximum=\"${kind.max}\" StepFrequency=\"${kind.step ?: 1.0}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("value" in node.bindings) "" else " ValueChanged=\"OnSliderChanged\"") +
                    "$visible$enabled$automation />"
            is NodeKind.Picker ->
                "$i<ComboBox SelectedValue=\"${node.xamlValue("selected", kind.selected.xml())}\" SelectedValuePath=\"Tag\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("selected" in node.bindings) "" else " SelectionChanged=\"OnSelectionChanged\"") +
                    "$visible$enabled>\n" +
                    kind.options.joinToString("\n") {
                        "${"    ".repeat(depth + 1)}<ComboBoxItem Content=\"${it.xamlText(node)}\" Tag=\"${it.value.xml()}\" />"
                    } + "\n$i</ComboBox>"
            is NodeKind.DatePicker -> datePicker(node, kind, i, visible, enabled)
            is NodeKind.Checkbox ->
                "$i<CheckBox Content=\"${node.xamlText(LocalizedField.Label, kind.label.orEmpty())}\" IsChecked=\"${node.xamlValue("checked", kind.checked.toString())}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("checked" in node.bindings) "" else " Click=\"OnCheckboxChanged\"") +
                    "$visible$enabled$automation />"
            NodeKind.Divider ->
                "$i<Border Height=\"1\" Background=\"{ThemeResource SystemControlForegroundBaseLowBrush}\" />"
            NodeKind.Card ->
                "$i<Border CornerRadius=\"8\" Padding=\"16\" Background=\"{ThemeResource CardBackgroundFillColorDefaultBrush}\">\n${child(1)}\n$i</Border>"
            is NodeKind.Chip ->
                "$i<Border CornerRadius=\"12\" Padding=\"8,4\" Background=\"{ThemeResource AccentFillColorDefaultBrush}\"><TextBlock Text=\"${node.xamlText(LocalizedField.Label, kind.label)}\" /></Border>"
            is NodeKind.ContentPicker ->
                "$i<Button Content=\"${node.xamlText(LocalizedField.Label, kind.label)}\" Tag=\"${kind.onRequest.xml()}\" Click=\"OnAction\"${kind.variant.winUiButtonStyle()}$visible$enabled$automation />"
        }
        val rendered = if (visibleBinding == null) {
            generated
        } else {
            val property = visibleBinding.path.replaceFirstChar(Char::uppercaseChar)
            """
            |$i<Border$outerVisibility>
            |$i    <Border.Transitions>
            |$i        <TransitionCollection>
            |$i            <${node.transition.winUiTransition()} />
            |$i        </TransitionCollection>
            |$i    </Border.Transitions>
            |${generated.prependIndent("    ")}
            |$i</Border>
            |""".trimMargin().trimEnd()
        }
        return marker + rendered
    }

    private fun datePicker(
        node: Node,
        kind: NodeKind.DatePicker,
        indentation: String,
        visible: String,
        enabled: String,
    ): String {
        val property = requireNotNull(node.bindings["value"])
            .path
            .replaceFirstChar(Char::uppercaseChar)
        return when (kind.mode) {
            DatePickerMode.Date ->
                "$indentation<CalendarDatePicker Date=\"{x:Bind State.$property, Mode=TwoWay}\"$visible$enabled />"
            DatePickerMode.Time ->
                "$indentation<TimePicker SelectedTime=\"{x:Bind State.$property, Mode=TwoWay}\"$visible$enabled />"
            DatePickerMode.DateTime ->
                "$indentation<StackPanel Orientation=\"Horizontal\" Spacing=\"8\"$visible>\n" +
                    "$indentation    <CalendarDatePicker Date=\"{x:Bind State.${property}Date, Mode=TwoWay}\"$enabled />\n" +
                    "$indentation    <TimePicker SelectedTime=\"{x:Bind State.${property}Time, Mode=TwoWay}\"$enabled />\n" +
                    "$indentation</StackPanel>"
        }
    }

    private fun input(
        node: Node,
        kind: NodeKind.Input,
        i: String,
        visible: String,
        enabled: String,
        automation: String,
    ): String {
        val control = if (kind.secure || kind.inputType == InputType.Password) {
            "PasswordBox"
        } else {
            "TextBox"
        }
        val value = if (control == "PasswordBox") "Password" else "Text"
        val content = node.xamlValue("value", kind.value.xml())
        val change = if ("value" in node.bindings) {
            ""
        } else if (control == "PasswordBox") {
            " PasswordChanged=\"OnPasswordChanged\""
        } else {
            " TextChanged=\"OnTextChanged\""
        }
        return "$i<$control $value=\"$content\" PlaceholderText=\"${node.xamlText(LocalizedField.Placeholder, kind.placeholder.orEmpty())}\" Tag=\"${kind.onChange.xml()}\"$change$visible$enabled$automation />"
    }

    private fun codeBehind(
        document: UiDocument,
        typeName: String,
        localization: LocalizationRegistry,
    ): String {
        val properties = document.root.bindingProperties()
        val navigations = document.root.winUiNavigations()
        val localizedProperties = document.root.winLocalizedProperties()
        val localizedMembers = localizedProperties.joinToString("\n") { property ->
            val expression = localization.render(target, property.text)
                ?: "Localize(\"${property.text.key.csharp()}\", \"${property.text.fallback.csharp()}\")"
            "    public string ${property.propertyName} => $expression;"
        }.let { if (it.isEmpty()) "" else "$it\n" }
        val nativeLocalization = winUiNativeLocalization(localizedProperties, localization)
        val localizationInterface = if (localizedProperties.isEmpty()) {
            ""
        } else {
            ", INotifyPropertyChanged"
        }
        val localizationEvent = if (localizedProperties.isEmpty()) {
            ""
        } else {
            "    public event PropertyChangedEventHandler? PropertyChanged;\n"
        }
        val localizationRefresh = if (localizedProperties.isEmpty()) {
            ""
        } else {
            val configureContext = if (nativeLocalization.isEmpty()) {
                ""
            } else {
                "        ConfigureLocalization(languageTag);\n"
            }
            val notifications = localizedProperties.joinToString("\n") {
                "        PropertyChanged?.Invoke(this, " +
                    "new(nameof(${it.propertyName})));"
            }
            """
            |    public void RefreshLocalization(string? languageTag = null)
            |    {
            |$configureContext$notifications
            |    }
            |
            |""".trimMargin()
        }
        val stateName = "${typeName}State"
        val stateProperty = if (properties.isEmpty()) {
            ""
        } else {
            "    public $stateName State { get; }\n"
        }
        val stateInitialization = if (properties.isEmpty()) {
            ""
        } else {
            "        State = new $stateName(dispatch, DispatcherQueue);\n"
        }
        val navigationFields = if (navigations.isEmpty()) {
            ""
        } else {
            "    private bool suppressNavigationSelection = true;\n"
        }
        val boundNavigations = navigations.filter { it.bindingProperty != null }
        val initialSelections = navigations.joinToString("\n") {
            val active = it.bindingProperty?.let { property -> "State.$property" }
                ?: "\"${it.active.csharp()}\""
            "        Apply${it.name}Selection($active);"
        }
        val navigationInitialization = if (navigations.isEmpty()) {
            ""
        } else {
            buildString {
                if (boundNavigations.isNotEmpty()) {
                    appendLine("        State.PropertyChanged += OnNavigationStateChanged;")
                }
                appendLine(initialSelections)
                appendLine("        suppressNavigationSelection = false;")
            }
        }
        val navigationStateHandler = if (boundNavigations.isEmpty()) {
            ""
        } else {
            boundNavigations.joinToString(
                separator = "\n",
                prefix = "    private void OnNavigationStateChanged(object? sender, PropertyChangedEventArgs e)\n    {\n",
                postfix = "\n    }\n\n",
            ) {
                val property = requireNotNull(it.bindingProperty)
                "        if (e.PropertyName == nameof(State.$property)) " +
                    "Apply${it.name}Selection(State.$property);"
            }
        }
        val navigationMembers = navigationStateHandler + navigations.joinToString(
            separator = "\n\n",
            transform = ::winUiNavigationMembers,
        ).let { if (it.isEmpty()) "" else "$it\n\n" }
        val stateClass = if (properties.isEmpty()) {
            ""
        } else {
            "\n" + csharpStateClass(stateName, properties)
        }
        return """
            |// Generated by CrossUI. Do not edit.
            |using System;
            |using System.ComponentModel;
            |using System.Globalization;
            |using System.Runtime.CompilerServices;
            |using Microsoft.UI.Dispatching;
            |using Microsoft.UI.Xaml;
            |using Microsoft.UI.Xaml.Controls;
            |using Microsoft.UI.Xaml.Controls.Primitives;
            |
            |namespace CrossUi.Generated;
            |
            |public sealed partial class $typeName : UserControl$localizationInterface
            |{
            |    public Action<string, string?> Dispatch { get; }
            |$stateProperty$localizedMembers$localizationEvent$navigationFields
            |    public $typeName() : this((_, _) =>
            |        throw new InvalidOperationException(
            |            "$typeName requires an action dispatcher."
            |        ))
            |    {
            |    }
            |
            |    public $typeName(Action<string, string?> dispatch)
            |    {
            |        Dispatch = dispatch;
            |$stateInitialization        InitializeComponent();
            |$navigationInitialization
            |    }
            |
            |$localizationRefresh$nativeLocalization$navigationMembers
            |    public Visibility BooleanToVisibility(bool value) =>
            |        value ? Visibility.Visible : Visibility.Collapsed;
            |
            |    private void OnAction(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, null);
            |
            |    private void OnTextChanged(object sender, TextChangedEventArgs e) =>
            |        DispatchTag(sender, ((TextBox)sender).Text);
            |
            |    private void OnPasswordChanged(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, ((PasswordBox)sender).Password);
            |
            |    private void OnToggleChanged(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, ((ToggleSwitch)sender).IsOn.ToString().ToLowerInvariant());
            |
            |    private void OnCheckboxChanged(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, (((CheckBox)sender).IsChecked ?? false).ToString().ToLowerInvariant());
            |
            |    private void OnSliderChanged(object sender, RangeBaseValueChangedEventArgs e) =>
            |        DispatchTag(sender, e.NewValue.ToString(CultureInfo.InvariantCulture));
            |
            |    private void OnSelectionChanged(object sender, SelectionChangedEventArgs e) =>
            |        DispatchTag(sender, ((ComboBox)sender).SelectedItem is FrameworkElement item ? item.Tag?.ToString() : null);
            |
            |    private void DispatchTag(object sender, string? value)
            |    {
            |        if (sender is FrameworkElement element && element.Tag is string action)
            |        {
            |            Dispatch(action, value);
            |        }
            |    }
            |}
            |$stateClass
            |""".trimMargin().trimEnd() + "\n"
    }

}
