package dev.crossui.compiler

import dev.crossui.ir.*
import dev.crossui.legalizer.ResolvedDocument

internal object WinUiGenerator : CodeGenerator {
    override val target = ExportTarget.WinUi3

    override fun generate(
        document: ResolvedDocument,
        typeName: String,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): List<GeneratedSource> {
        val body = xamlNode(
            document.document.root,
            2,
            nativeViews,
            localization,
        )
        return listOf(
            GeneratedSource(
                target,
                target.outputFileName(typeName),
                """
                |<!-- Generated by CrossUI. Do not edit. -->
                |<UserControl
                |    x:Class="CrossUi.Generated.$typeName"
                |    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                |    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
                |    <ScrollViewer>
                |$body
                |    </ScrollViewer>
                |</UserControl>
                |""".trimMargin(),
            ),
            GeneratedSource(
                target,
                "$typeName.xaml.cs",
                codeBehind(document.document, typeName, localization),
            ),
        )
    }

    private fun xamlNode(
        node: Node,
        depth: Int,
        nativeViews: NativeViewRegistry,
        localization: LocalizationRegistry,
    ): String {
        val i = "    ".repeat(depth)
        val marker = "$i<!-- crossui-node:${node.key.value} -->\n"
        val child = { extra: Int ->
            node.children.joinToString("\n") {
                xamlNode(it, depth + extra, nativeViews, localization)
            }
        }
        val enabled = node.bindings["enabled"]?.let {
            " IsEnabled=\"{x:Bind State.${it.path.replaceFirstChar(Char::uppercaseChar)}, Mode=OneWay}\""
        } ?: if (node.semantics.enabled) "" else " IsEnabled=\"False\""
        val visible = node.bindings["visible"]?.let {
            " Visibility=\"{x:Bind BooleanToVisibility(State.${it.path.replaceFirstChar(Char::uppercaseChar)}), Mode=OneWay}\""
        }.orEmpty()
        val automation = node.semantics.label?.let {
            " AutomationProperties.Name=\"${it.xml()}\""
        }.orEmpty()
        val generated = when (val kind = node.kind) {
            is NodeKind.Text ->
                "$i<TextBlock Text=\"${node.xamlValue("value", node.xamlText(LocalizedField.Value, kind.text), "OneWay")}\"$visible$automation />"
            is NodeKind.Button ->
                "$i<Button Content=\"${node.xamlText(LocalizedField.Label, kind.label)}\" Tag=\"${kind.action.xml()}\" Click=\"OnAction\"$visible$enabled$automation />"
            is NodeKind.Input -> input(node, kind, i, visible, enabled, automation)
            is NodeKind.Stack -> {
                val orientation = if (kind.axis == Axis.Horizontal) {
                    "Horizontal"
                } else {
                    "Vertical"
                }
                "$i<StackPanel Orientation=\"$orientation\" Spacing=\"${spacing(kind.spacing)}\">\n${child(1)}\n$i</StackPanel>"
            }
            is NodeKind.ListNode ->
                "$i<StackPanel Tag=\"${kind.onSelect.orEmpty().xml()}\">\n${child(1)}\n$i</StackPanel>"
            NodeKind.Form -> "$i<StackPanel Spacing=\"16\">\n${child(1)}\n$i</StackPanel>"
            is NodeKind.Loading -> "$i<ProgressRing IsActive=\"True\"$visible />"
            is NodeKind.Navigation -> {
                val selected = node.children.firstOrNull { it.key.value == kind.active }
                    ?: node.children.firstOrNull()
                "$i<NavigationView PaneDisplayMode=\"${if (kind.mode == NavigationMode.Tab) "Top" else "Left"}\">\n" +
                    "${"    ".repeat(depth + 1)}<NavigationView.Content>\n" +
                    selected?.let {
                        xamlNode(it, depth + 2, nativeViews, localization)
                    }.orEmpty() +
                    "\n${"    ".repeat(depth + 1)}</NavigationView.Content>\n$i</NavigationView>"
            }
            is NodeKind.Route ->
                "$i<StackPanel Spacing=\"16\">\n${child(1)}\n$i</StackPanel>"
            is NodeKind.PlatformView -> nativeViews.render(
                target,
                kind.name,
                kind.payload.toString(),
            )?.prependIndent(i) ?: throw missingNativeView(kind.name, target)
            is NodeKind.Toggle ->
                "$i<ToggleSwitch Header=\"${node.xamlText(LocalizedField.Label, kind.label.orEmpty())}\" IsOn=\"${node.xamlValue("checked", kind.checked.toString())}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("checked" in node.bindings) "" else " Toggled=\"OnToggleChanged\"") +
                    "$visible$enabled$automation />"
            is NodeKind.Image ->
                "$i<Image Source=\"${kind.src.xml()}\" AutomationProperties.Name=\"${node.xamlText(LocalizedField.Alt, kind.alt.orEmpty())}\" />"
            is NodeKind.Dialog ->
                "$i<!-- ContentDialog Title=\"${kind.title.xml()}\" PrimaryButtonText=\"${kind.confirmLabel.orEmpty().xml()}\" CloseButtonText=\"${kind.cancelLabel.orEmpty().xml()}\" -->"
            is NodeKind.Slider ->
                "$i<Slider Value=\"${node.xamlValue("value", kind.value.toString())}\" Minimum=\"${kind.min}\" Maximum=\"${kind.max}\" StepFrequency=\"${kind.step ?: 1.0}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("value" in node.bindings) "" else " ValueChanged=\"OnSliderChanged\"") +
                    "$visible$enabled$automation />"
            is NodeKind.Picker ->
                "$i<ComboBox SelectedValue=\"${node.xamlValue("selected", kind.selected.xml())}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("selected" in node.bindings) "" else " SelectionChanged=\"OnSelectionChanged\"") +
                    "$visible$enabled>\n" +
                    kind.options.joinToString("\n") {
                        "${"    ".repeat(depth + 1)}<ComboBoxItem Content=\"${it.xamlText(node)}\" Tag=\"${it.value.xml()}\" />"
                    } + "\n$i</ComboBox>"
            is NodeKind.DatePicker -> when (kind.mode) {
                DatePickerMode.Time ->
                    "$i<TimePicker Tag=\"${kind.onChange.xml()}\" SelectedTimeChanged=\"OnTimeChanged\"$visible$enabled />"
                else ->
                    "$i<CalendarDatePicker Tag=\"${kind.onChange.xml()}\" DateChanged=\"OnDateChanged\"$visible$enabled />"
            }
            is NodeKind.Checkbox ->
                "$i<CheckBox Content=\"${node.xamlText(LocalizedField.Label, kind.label.orEmpty())}\" IsChecked=\"${node.xamlValue("checked", kind.checked.toString())}\" Tag=\"${kind.onChange.xml()}\"" +
                    (if ("checked" in node.bindings) "" else " Click=\"OnCheckboxChanged\"") +
                    "$visible$enabled$automation />"
            NodeKind.Divider ->
                "$i<Border Height=\"1\" Background=\"{ThemeResource SystemControlForegroundBaseLowBrush}\" />"
            NodeKind.Card ->
                "$i<Border CornerRadius=\"8\" Padding=\"16\" Background=\"{ThemeResource CardBackgroundFillColorDefaultBrush}\">\n${child(1)}\n$i</Border>"
            is NodeKind.Chip ->
                "$i<Border CornerRadius=\"12\" Padding=\"8,4\" Background=\"{ThemeResource AccentFillColorDefaultBrush}\"><TextBlock Text=\"${node.xamlText(LocalizedField.Label, kind.label)}\" /></Border>"
        }
        return marker + generated
    }

    private fun input(
        node: Node,
        kind: NodeKind.Input,
        i: String,
        visible: String,
        enabled: String,
        automation: String,
    ): String {
        val control = if (kind.secure || kind.inputType == InputType.Password) {
            "PasswordBox"
        } else {
            "TextBox"
        }
        val value = if (control == "PasswordBox") "Password" else "Text"
        val content = node.xamlValue("value", kind.value.xml())
        val change = if ("value" in node.bindings) {
            ""
        } else if (control == "PasswordBox") {
            " PasswordChanged=\"OnPasswordChanged\""
        } else {
            " TextChanged=\"OnTextChanged\""
        }
        return "$i<$control $value=\"$content\" PlaceholderText=\"${node.xamlText(LocalizedField.Placeholder, kind.placeholder.orEmpty())}\" Tag=\"${kind.onChange.xml()}\"$change$visible$enabled$automation />"
    }

    private fun codeBehind(
        document: UiDocument,
        typeName: String,
        localization: LocalizationRegistry,
    ): String {
        val properties = document.root.bindingProperties()
        val localizedProperties = document.root.winLocalizedProperties()
        val localizedMembers = localizedProperties.joinToString("\n") { property ->
            val expression = localization.render(target, property.text)
                ?: "Localize(\"${property.text.key.csharp()}\", \"${property.text.fallback.csharp()}\")"
            "    public string ${property.propertyName} => $expression;"
        }.let { if (it.isEmpty()) "" else "$it\n" }
        val nativeLocalization = nativeLocalization(localizedProperties, localization)
        val stateName = "${typeName}State"
        val stateProperty = if (properties.isEmpty()) {
            ""
        } else {
            "    public $stateName State { get; }\n"
        }
        val stateInitialization = if (properties.isEmpty()) {
            ""
        } else {
            "        State = new $stateName(dispatch);\n"
        }
        val stateClass = if (properties.isEmpty()) {
            ""
        } else {
            "\n" + csharpStateClass(stateName, properties)
        }
        return """
            |// Generated by CrossUI. Do not edit.
            |using System;
            |using System.ComponentModel;
            |using System.Globalization;
            |using System.Runtime.CompilerServices;
            |using Microsoft.UI.Xaml;
            |using Microsoft.UI.Xaml.Controls;
            |using Microsoft.UI.Xaml.Controls.Primitives;
            |
            |namespace CrossUi.Generated;
            |
            |public sealed partial class $typeName : UserControl
            |{
            |    public Action<string, string?> Dispatch { get; }
            |$stateProperty$localizedMembers
            |    public $typeName() : this((_, _) => { })
            |    {
            |    }
            |
            |    public $typeName(Action<string, string?> dispatch)
            |    {
            |        Dispatch = dispatch;
            |$stateInitialization        InitializeComponent();
            |    }
            |
            |$nativeLocalization
            |    public Visibility BooleanToVisibility(bool value) =>
            |        value ? Visibility.Visible : Visibility.Collapsed;
            |
            |    private void OnAction(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, null);
            |
            |    private void OnTextChanged(object sender, TextChangedEventArgs e) =>
            |        DispatchTag(sender, ((TextBox)sender).Text);
            |
            |    private void OnPasswordChanged(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, ((PasswordBox)sender).Password);
            |
            |    private void OnToggleChanged(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, ((ToggleSwitch)sender).IsOn.ToString().ToLowerInvariant());
            |
            |    private void OnCheckboxChanged(object sender, RoutedEventArgs e) =>
            |        DispatchTag(sender, (((CheckBox)sender).IsChecked ?? false).ToString().ToLowerInvariant());
            |
            |    private void OnSliderChanged(object sender, RangeBaseValueChangedEventArgs e) =>
            |        DispatchTag(sender, e.NewValue.ToString(CultureInfo.InvariantCulture));
            |
            |    private void OnSelectionChanged(object sender, SelectionChangedEventArgs e) =>
            |        DispatchTag(sender, ((ComboBox)sender).SelectedItem is FrameworkElement item ? item.Tag?.ToString() : null);
            |
            |    private void OnDateChanged(CalendarDatePicker sender, CalendarDatePickerDateChangedEventArgs e) =>
            |        DispatchTag(sender, e.NewDate?.ToString("O"));
            |
            |    private void OnTimeChanged(TimePicker sender, TimePickerSelectedValueChangedEventArgs e) =>
            |        DispatchTag(sender, e.NewTime?.ToString());
            |
            |    private void DispatchTag(object sender, string? value)
            |    {
            |        if (sender is FrameworkElement element && element.Tag is string action)
            |        {
            |            Dispatch(action, value);
            |        }
            |    }
            |}
            |$stateClass
            |""".trimMargin().trimEnd() + "\n"
    }

    private fun nativeLocalization(
        properties: List<WinLocalizedProperty>,
        localization: LocalizationRegistry,
    ): String = if (
        properties.any { localization.render(target, it.text) == null }
    ) {
        """
        |    private readonly Microsoft.Windows.ApplicationModel.Resources.ResourceLoader resourceLoader = new();
        |
        |    private string Localize(string key, string fallback)
        |    {
        |        try
        |        {
        |            var value = resourceLoader.GetString(key);
        |            return string.IsNullOrEmpty(value) ? fallback : value;
        |        }
        |        catch
        |        {
        |            return fallback;
        |        }
        |    }
        |
        |""".trimMargin()
    } else {
        ""
    }

    private fun csharpStateClass(
        stateName: String,
        properties: List<WinBindingProperty>,
    ): String {
        val members = properties.joinToString("\n\n", transform = ::stateMember)
        return """
            |public sealed class $stateName : INotifyPropertyChanged
            |{
            |    private readonly Action<string, string?> dispatch;
            |
            |    public $stateName(Action<string, string?> dispatch)
            |    {
            |        this.dispatch = dispatch;
            |    }
            |
            |    public event PropertyChangedEventHandler? PropertyChanged;
            |
            |$members
            |}
            |""".trimMargin()
    }

    private fun stateMember(property: WinBindingProperty): String {
        val field = property.propertyName.replaceFirstChar(Char::lowercaseChar)
        val serialize = when (property.csharpType) {
            "bool" -> "value.ToString().ToLowerInvariant()"
            "double" -> "value.ToString(CultureInfo.InvariantCulture)"
            else -> "value"
        }
        val dispatch = property.action?.let {
            """
            |        if (dispatchChange)
            |        {
            |            dispatch("${it.csharp()}", $serialize);
            |        }
            |""".trimMargin()
        }.orEmpty()
        return """
        |    private ${property.csharpType} $field = ${property.defaultValue};
        |
        |    public ${property.csharpType} ${property.propertyName}
        |    {
        |        get => $field;
        |        set => Set${property.propertyName}(value, true);
        |    }
        |
        |    public void Apply${property.propertyName}(${property.csharpType} value) =>
        |        Set${property.propertyName}(value, false);
        |
        |    private void Set${property.propertyName}(${property.csharpType} value, bool dispatchChange)
        |    {
        |        if (Equals($field, value))
        |        {
        |            return;
        |        }
        |
        |        $field = value;
        |        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(${property.propertyName})));
        |$dispatch    }
        |""".trimMargin()
    }
}
